artifact_location: file:C:/Users/R I B/OneDrive/Bureau/IA/runs/mlflow/420627894996664630
creation_time: 1766880174467
experiment_id: '420627894996664630'
last_update_time: 1766880174467
lifecycle_stage: active
name: C:\Users\R I B\OneDrive\Bureau\IA\models
